Repository nanoframework/CoreLibrary, pull requests merged in 2018-10, with the labels that each got.

#34 Work on CI
  GitVersion.yml
  appveyor-discord.ps1
  appveyor.yml
  commit-assemblyinfo-changes.ps1
Labels: Area: Config-and-Build

#35 Update branch name for version update
  commit-assemblyinfo-changes.ps1
Labels: Area: Config-and-Build

#37 Work CI
  appveyor-discord.ps1
  appveyor.yml
  commit-assemblyinfo-changes.ps1
Labels: Area: Config-and-Build

#47 Improve CI & CD
  commit-assemblyinfo-changes.ps1
  generate-change-log.ps1
  update-dependencies.ps1
Labels: Area: Config-and-Build

#48 Fix issues with AppVeyor yaml
  appveyor.yml
  commit-assemblyinfo-changes.ps1
  install-vsix-appveyor.ps1
Labels: Area: Config-and-Build

#49 Add Hardware.Stm32 to dependencies to update
  update-dependencies.ps1
Labels: Area: Config-and-Build

#50 Extract System.Math (except max, min and abs) +semver:minor
  source/nanoFramework.CoreLibrary/System/Math.cs
Labels: Breaking-Change

#51 Work extracting System.Math
  source/nanoFramework.CoreLibrary/CoreLibrary.nfproj
  source/nanoFramework.CoreLibrary/Friends.cs
  source/nanoFramework.CoreLibrary/System/Math.cs
  source/nanoFramework.CoreLibrary/System/String.cs
  source/nanoFramework.CoreLibrary/System/Text/StringBuilder.cs
Labels: Area: Config-and-Build

#53 Work on CD/CI
  commit-assemblyinfo-changes.ps1
  generate-change-log.ps1
  update-dependencies.ps1
Labels: Area: Config-and-Build

#54 Work CD/CI
  commit-assemblyinfo-changes.ps1
  generate-change-log.ps1
  update-dependencies.ps1
Labels: Area: Config-and-Build

#55 Fix bug in FromBase64CharArray
  source/nanoFramework.CoreLibrary/System/Convert.cs
Labels: Type: bug
