Repository nanoframework/CoreLibrary, pull requests merged in 2018-09, with the labels that each got.

#23 Fix Hashtable.CopyTo
  source/System/Collections/HashTable.cs
Labels: Type: bug

#24 Constructor should copy only the desired chars
  source/System/Text/StringBuilder.cs
Labels: Type: bug

#25 Fix PostProcessInteger in System.Number
  source/System/Number.cs
Labels: Type: bug

#26 Fix Assembly.GetType(string, bool) throws ArgumentException
  source/System/Reflection/Assembly.cs
Labels: Type: bug

#28 Add option to remove AppDomains APIs with compiler constant
  source/CoreLibrary.nfproj
  source/System/AppDomain.cs
  source/System/Threading/Thread.cs
Labels: Area: Config-and-Build

#27 Add GetCustomAttributes method to MemberInfo and derived classes
  source/System/Reflection/ConstructorInfo.cs
  source/System/Reflection/FieldInfo.cs
  source/System/Reflection/MemberInfo.cs
  source/System/Reflection/RuntimeMethodInfo.cs
  source/System/RuntimeType.cs
Labels: Type: enhancement

#29 Work on CI
  .github_changelog_generator
  appveyor.yml
  generate-change-log.ps1
  install-vsix-appveyor.ps1
Labels: Area: Config-and-Build

#30 Update file encoding to UTF-8
  source/System/AssemblyInfo2.cs
Labels: Area: Config-and-Build

#32 Fix for AppVeyor build
  GitVersion.yml
  appveyor.yml
Labels: Area: Config-and-Build

#33 Fix for commiting assembly info changes in AppVeyor
  appveyor.yml
  commit-assemblyinfo-changes.ps1
Labels: Area: Config-and-Build
