Repository nanoframework/CoreLibrary, pull requests merged in 2018-06, with the labels that each got.

#11 Add Timeout.InfiniteTimeSpan and Sleep(timespan)
  source/CoreLibrary.nfproj
  source/System/Threading/Thread.cs
  source/System/Threading/Timeout.cs
Labels: Type: enhancement

#12 Add String.Format
  source/System/String.cs
Labels: Status: merge OK, Type: enhancement

#13 Add overloads with float parameters to Math methods
  source/System/Math.cs
Labels: Type: enhancement

#14 Work on TimeSpan
  source/System/DateTime.cs
  source/System/TimeSpan.cs
Labels: Status: Waiting for native support, Type: enhancement

#15 Work on Convert() class
  source/System/Convert.cs
Labels: documentation
