Repository nanoframework/CoreLibrary, pull requests merged in 2019-04, with the labels that each got.

#66 Fix typo in TimeSpan
  source/nanoFramework.CoreLibrary/System/IO/Stream.cs
  source/nanoFramework.CoreLibrary/System/TimeSpan.cs
Labels: Type: bug, Type: documentation

#67 Add AssemblyNativeVersionAttribute
  source/nanoFramework.CoreLibrary/CoreLibrary.nfproj
  source/nanoFramework.CoreLibrary/System/AssemblyInfo2.cs
  source/nanoFramework.CoreLibrary/System/Reflection/AssemblyAttributes.cs
Labels: Breaking-Change, Type: enhancement

#68 Update GitVersioning NuGet
  source/nanoFramework.CoreLibrary/CoreLibrary.nfproj
  source/nanoFramework.CoreLibrary/packages.config
Labels: Type: dependencies
