Repository nanoframework/CoreLibrary, pull requests merged in 2020-09, with the labels that each got.

#108 Remove System.Decimal from build
  nanoFramework.CoreLibrary.NoReflection/CoreLibrary.NoReflection.nfproj
  nanoFramework.CoreLibrary/CoreLibrary.nfproj
  nanoFramework.CoreLibrary/System/Decimal.cs
Labels: Breaking-Change

#109 Adding SpanByte to System
  nanoFramework.CoreLibrary.NoReflection/CoreLibrary.NoReflection.nfproj
  nanoFramework.CoreLibrary/CoreLibrary.nfproj
  nanoFramework.CoreLibrary/System/SpanByte.cs
Labels: CI: Publish Release, CI: Update Dependents, Type: enhancement

#110 Small correction on SpanByte
  nanoFramework.CoreLibrary/System/SpanByte.cs
Labels: Type: bug
