Repository nanoframework/CoreLibrary, pull requests merged in 2021-03, with the labels that each got.

#118 ToString() reimplementation
  nanoFramework.CoreLibrary/System/AssemblyInfo.cs
  nanoFramework.CoreLibrary/System/Number.cs
Labels: Type: bug, Type: enhancement

#120 Fix comparer in GUID
  nanoFramework.CoreLibrary/System/Guid.cs
Labels: Type: bug

#121 Fixing Convert with whitespaces
  nanoFramework.CoreLibrary/System/Convert.cs
Labels: Type: bug

#123 Fix case of Double.NaN
  Tests/NFUnitTestSystemLib/UnitTestTypeTests.cs
  nanoFramework.CoreLibrary/System/Double.cs
Labels: Type: bug

#122 Fixed bad test expectations in String Tests
  Tests/NFUnitTestSystemLib/UnitTestStringTests.cs
Labels: Type: bug

#126 Remove Console class
  nanoFramework.CoreLibrary/Friends.cs
  nanoFramework.CoreLibrary/System/AssemblyInfo.cs
  nanoFramework.CoreLibrary/System/Console.cs
  nanoFramework.CoreLibrary/System/Diagnostics/Debug.cs
  version.json
Labels: Breaking-Change
