Repository nanoframework/CoreLibrary, pull requests merged in 2021-05, with the labels that each got.

#132 Added nanoFramework.Logging to InternalsIsVisibleTo
  nanoFramework.CoreLibrary/Friends.cs
Labels: Type: enhancement

#133 Update NuGets
  Tests/NFUnitTest_DummyAdapter/NFUnitTest_DummyAdapter.nfproj
  Tests/NFUnitTest_DummyAdapter/packages.config
  nanoFramework.CoreLibrary.NoReflection/CoreLibrary.NoReflection.nfproj
  nanoFramework.CoreLibrary.NoReflection/packages.config
  nanoFramework.CoreLibrary/CoreLibrary.nfproj
  nanoFramework.CoreLibrary/packages.config
Labels: Type: dependencies

#134 Work CI-CD
  nanoFramework.CoreLibrary.DELIVERABLES.nuspec
  nanoFramework.CoreLibrary.NoReflection.nuspec
Labels: Area: Config-and-Build

#135 Add Convert.ToByte(bool)
  Tests/NFUnitTestConversions/UnitTestConvertTests.cs
  nanoFramework.CoreLibrary/System/AssemblyInfo.cs
  nanoFramework.CoreLibrary/System/Convert.cs
Labels: Type: enhancement

#136 Add SpinWait
  nanoFramework.CoreLibrary/CoreLibrary.nfproj
  nanoFramework.CoreLibrary/System/AssemblyInfo.cs
  nanoFramework.CoreLibrary/System/Threading/SpinWait.cs
  nanoFramework.CoreLibrary/System/Threading/Thread.cs
  version.json
Labels: Type: enhancement

#137 Add TimeoutException
  Tests/NFUnitTestException/NFUnitTestException.nfproj
  Tests/NFUnitTestException/UnitTestExceptionTests.cs
  nanoFramework.CoreLibrary/CoreLibrary.nfproj
  nanoFramework.CoreLibrary/System/AssemblyInfo.cs
  nanoFramework.CoreLibrary/System/TimeoutException.cs
Labels: Type: Unit Tests, Type: enhancement

#138 Add timeout exception to no reflection project
  nanoFramework.CoreLibrary.NoReflection/CoreLibrary.NoReflection.nfproj
Labels: Type: enhancement

#141 Fixed unit tests NFUnitTestConversions
  Tests/NFUnitTestConversions/UnitTestConvertTests.cs
  nanoFramework.CoreLibrary/System/Convert.cs
Labels: Type: Unit Tests

#140 Fix access beyond array boundaries in SpanByte
  nanoFramework.CoreLibrary/System/SpanByte.cs
Labels: Type: bug

#142 Fixes for unit tests for CoreLibrary
  Tests/NFUnitTestSystemLib/UnitTestParseTests.cs
  Tests/NFUnitTestSystemLib/UnitTestTypeTests.cs
  nanoFramework.CoreLibrary.NoReflection/CoreLibrary.NoReflection.nfproj
  nanoFramework.CoreLibrary/CoreLibrary.nfproj
  nanoFramework.CoreLibrary/System/AssemblyInfo.cs
  nanoFramework.CoreLibrary/System/FormatException.cs
  version.json
Labels: Type: Unit Tests, Type: enhancement
