Repository nanoframework/CoreLibrary, pull requests merged in 2022-03, with the labels that each got.

#179 Fix Single.cs comment
  nanoFramework.CoreLibrary/System/Single.cs
Labels: Type: documentation

#180 Fix RuntimeFeature.cs comment
  nanoFramework.CoreLibrary/System/Runtime/CompilerServices/RuntimeFeature.cs
Labels: Type: documentation

#181 Fix Thread.cs comment
  nanoFramework.CoreLibrary/System/Threading/Thread.cs
Labels: Type: documentation

#178 Rework SpanByte
  nanoFramework.CoreLibrary/System/SpanByte.cs
Labels: Type: enhancement, Type: documentation

#177 Add support for multi parameter constructors in attributes
  nanoFramework.CoreLibrary/System/Reflection/CustomAttributesHelpers.cs
Labels: Type: enhancement

#182 Fix SpanByte for edge cases
  Tests/NFUnitTestTypes/NFUnitTestTypes.nfproj
  Tests/NFUnitTestTypes/UnitTestsSpanByte.cs
  nanoFramework.CoreLibrary/System/SpanByte.cs
Labels: Type: bug, Type: Unit Tests
