Repository nanoframework/CoreLibrary, pull requests merged in 2025-01, with the labels that each got.

#218 Improve attribute constructor handling when calling `Type.GetCustomAttributes()`
  Tests/NFUnitTestAttributes/ConstructorTests.cs
  Tests/NFUnitTestAttributes/NFUnitTestAttributes.nfproj
  nanoFramework.CoreLibrary/System/Reflection/CustomAttributesHelpers.cs
Labels: Type: bug, Type: Unit Tests

#220 Add `ExcludeFromStubs` attribute
  nanoFramework.CoreLibrary.NoReflection/CoreLibrary.NoReflection.nfproj
  nanoFramework.CoreLibrary/CoreLibrary.nfproj
  nanoFramework.CoreLibrary/System/AttributeTargets.cs
  nanoFramework.CoreLibrary/System/AttributeUsageAttribute.cs
  nanoFramework.CoreLibrary/System/CLSCompliantAttribute.cs
  nanoFramework.CoreLibrary/System/ComponentModel/EditorBrowsableAttribute.cs
  nanoFramework.CoreLibrary/System/DBNull.cs
  nanoFramework.CoreLibrary/System/Diagnostics/ConditionalAttribute.cs
  nanoFramework.CoreLibrary/System/Diagnostics/DebuggerAttributes.cs
  nanoFramework.CoreLibrary/System/FlagsAttribute.cs
  nanoFramework.CoreLibrary/System/NonSerializedAttribute.cs
  nanoFramework.CoreLibrary/System/ObsoleteAttribute.cs
  nanoFramework.CoreLibrary/System/ParamArrayAttribute.cs
  nanoFramework.CoreLibrary/System/Reflection/AssemblyAttributes.cs
  nanoFramework.CoreLibrary/System/Reflection/AssemblyReflectionAttributes.cs
  nanoFramework.CoreLibrary/System/Reflection/BindingFlags.cs
  nanoFramework.CoreLibrary/System/Reflection/DefaultMemberAttribute.cs
  nanoFramework.CoreLibrary/System/Reflection/FieldReflectionAttributes.cs
  nanoFramework.CoreLibrary/System/Reflection/MethodImplAttributes.cs
  nanoFramework.CoreLibrary/System/Runtime/CompilerServices/ExcludeFromStubsAttribute.cs
  nanoFramework.CoreLibrary/System/Runtime/CompilerServices/IndexerNameAttribute.cs
  nanoFramework.CoreLibrary/System/Runtime/CompilerServices/InternalsVisibleToAttribute.cs
  nanoFramework.CoreLibrary/System/Runtime/CompilerServices/MethodImplAttribute.cs
  nanoFramework.CoreLibrary/System/Runtime/InteropServices/Attributes.cs
  nanoFramework.CoreLibrary/System/Runtime/InteropServices/CharSet.cs
  nanoFramework.CoreLibrary/System/Runtime/InteropServices/LayoutKind.cs
  nanoFramework.CoreLibrary/System/Runtime/Remoting/__TransparentProxy.cs
  nanoFramework.CoreLibrary/System/SerializableAttribute.cs
  nanoFramework.CoreLibrary/System/ThreadAttributes.cs
  nanoFramework.CoreLibrary/System/TypedReference.cs
  nanoFramework.CoreLibrary/System/UIntPtr.cs
Labels: Type: enhancement, Status: Waiting for native support

#222 Rework datetime handling in Convert
  nanoFramework.CoreLibrary/System/Convert.cs
Labels: Type: enhancement, Status: Waiting for native support

#221 Fix `UtcNow` and `Today`
  nanoFramework.CoreLibrary/System/DateTime.cs
Labels: Type: enhancement, Status: Waiting for native support

#219 Moving attributes from System.Runtime
  Tests/NFUnitTestAttributes/CallerArgumentExpressionAttributeTests.cs
  Tests/NFUnitTestAttributes/CallerMemberNameAttributeTests.cs
  Tests/NFUnitTestAttributes/NFUnitTestAttributes.nfproj
  nanoFramework.CoreLibrary.NoReflection/CoreLibrary.NoReflection.nfproj
  nanoFramework.CoreLibrary/CoreLibrary.nfproj
  nanoFramework.CoreLibrary/System/Diagnostics/CodeAnalysis/NullableAttributes.cs
  nanoFramework.CoreLibrary/System/Runtime/CompilerServices/CallerArgumentExpressionAttribute.cs
  nanoFramework.CoreLibrary/System/Runtime/CompilerServices/CallerMemberNameAttribute.cs
Labels: Type: enhancement

#223 Add null helpers to argument exceptions
  nanoFramework.CoreLibrary.NoReflection/CoreLibrary.NoReflection.nfproj
  nanoFramework.CoreLibrary/CoreLibrary.nfproj
  nanoFramework.CoreLibrary/System/ArgumentException.cs
  nanoFramework.CoreLibrary/System/ArgumentNullException.cs
  nanoFramework.CoreLibrary/System/String.cs
Labels: Type: enhancement, Status: Waiting for native support

#224 Prepare new release
  nanoFramework.CoreLibrary/System/AssemblyInfo.cs
  version.json
Labels: Area: Config-and-Build
