Repository nanoframework/CoreLibrary, pull requests merged in 2025-02, with the labels that each got.

#227 Add NativeProfiled attribute
  nanoFramework.CoreLibrary.NoReflection/CoreLibrary.NoReflection.nfproj
  nanoFramework.CoreLibrary/CoreLibrary.nfproj
  nanoFramework.CoreLibrary/System/Diagnostics/NativeProfiledAttribute.cs
Labels: Type: enhancement, Status: Waiting for native support

#228 Fix message for `ArgumentException`
  nanoFramework.CoreLibrary/System/ArgumentException.cs
Labels: Type: bug

#225 Add unit tests for new nullable attributes
  Tests/NFUnitTestAttributes/Diagnostics/CodeAnalysis/NullableAttributesTests.cs
  Tests/NFUnitTestAttributes/NFUnitTestAttributes.nfproj
  Tests/NFUnitTestAttributes/Runtime/CompilerServices/CallerArgumentExpressionAttributeTests.cs
  Tests/NFUnitTestAttributes/Runtime/CompilerServices/CallerMemberNameAttributeTests.cs
  Tests/NFUnitTestException/ArgumentExceptionTests.cs
  Tests/NFUnitTestException/ArgumentNullExceptionTests.cs
  Tests/NFUnitTestException/NFUnitTestException.nfproj
  nanoFramework.CoreLibrary.sln
Labels: Type: bug, Type: Unit Tests

#230 Add new unit tests for single and double types
  Tests/NFUnitTestSystemLib/UnitTestDouble.cs
  Tests/NFUnitTestSystemLib/UnitTestSingle.cs
Labels: Type: Unit Tests

#231 Migrate Assert to new API
  Tests/NFUnitTestTypes/UnitTestValueArrayTypess.cs
Labels: Type: Unit Tests

#232 Work and improvements in unit tests
  Tests/NFUnitTestConversions/UnitTestConvertTests.cs
  Tests/NFUnitTestSystemLib/UnitTestDateTime.cs
  Tests/NFUnitTestSystemLib/UnitTestDouble.cs
  Tests/NFUnitTestSystemLib/UnitTestReflectionMemberTest.cs
  Tests/NFUnitTestSystemLib/UnitTestReflectionTypeTest.cs
  Tests/NFUnitTestSystemLib/UnitTestSingle.cs
  Tests/NFUnitTestSystemLib/UnitTestTimeSpan.cs
  Tests/NFUnitTestSystemLib/UnitTestTypeTests.cs
  Tests/NFUnitTestTypes/UnitTestObjectTypeTests.cs
  Tests/NFUnitTestTypes/UnitTestValueArrayTypess.cs
  Tests/NFUnitTestTypes/UnitTestValueFloatTests.cs
  Tests/NFUnitTestTypes/UnitTestValueIntegralTests.cs
  Tests/NFUnitTestTypes/UnitTestValueSimpleTests.cs
Labels: Type: Unit Tests

#233 Rework `Guid`
  nanoFramework.CoreLibrary/System/Guid.cs
Labels: Type: enhancement

#234 Remove types to exclude from project file
  nanoFramework.CoreLibrary.NoReflection/CoreLibrary.NoReflection.nfproj
  nanoFramework.CoreLibrary/CoreLibrary.nfproj
  nanoFramework.CoreLibrary/System/ComponentModel/EditorBrowsableAttribute.cs
  nanoFramework.CoreLibrary/System/Convert.cs
  nanoFramework.CoreLibrary/System/DateTime.cs
  nanoFramework.CoreLibrary/System/DayOfWeek.cs
  nanoFramework.CoreLibrary/System/Decimal.cs
  nanoFramework.CoreLibrary/System/Diagnostics/DebuggerAttributes.cs
  nanoFramework.CoreLibrary/System/IO/IOException.cs
  nanoFramework.CoreLibrary/System/Reflection/AssemblyNameFlags.cs
  nanoFramework.CoreLibrary/System/Reflection/MemberTypes.cs
  nanoFramework.CoreLibrary/System/Runtime/CompilerServices/ExtensionAttribute.cs
  nanoFramework.CoreLibrary/System/Runtime/CompilerServices/MethodImplAttribute.cs
  nanoFramework.CoreLibrary/System/Threading/ThreadPriority.cs
  nanoFramework.CoreLibrary/System/Type.cs
Labels: Area: Config-and-Build

#235 Rework ArgumentNullException
  nanoFramework.CoreLibrary/System/Convert.cs
  nanoFramework.CoreLibrary/System/String.cs
  nanoFramework.CoreLibrary/System/TargetFrameworkAttribute.cs
Labels: Type: enhancement

#236 Bump version and assembly version
  nanoFramework.CoreLibrary/System/AssemblyInfo.cs
  version.json
Labels: Area: Config-and-Build, CI: Skip Unit Tests

#239 Fix inclusion of DefaultMemberAttribute in no reflection version
  nanoFramework.CoreLibrary/System/Reflection/DefaultMemberAttribute.cs
Labels: Area: Config-and-Build
